### ISSUE TITLE
there is some bug in Stroke animation button effect

### ISSUE THREAD

**Issue by CracKerMe** [comehope/front-end-daily-challenges#1]
you codepen link is here:   [https://codepen.io/comehope/pen/mKdzZM](https://codepen.io/comehope/pen/mKdzZM)  
when you zoomin the website, you will clearly find that the ::before element does not display above the border-top, there is 1px distance.

**Comment by comehope** [comment]
Thank you for your careful observation.
The problem is caused by the box-model and has been fixed.
