### ISSUE TITLE
033-milk-text-effect    请问.container里为什么缺了background-color：black之后效果差这么多？

### ISSUE THREAD

**Issue by zwmin** [comehope/front-end-daily-challenges#2]
.container {
  filter: contrast(10);
  background-color: black;
  overflow:hidden;
}
.container里面的前两条样式是如何起到关键作用的呢，看了好久也没明白，能不能给解释一下呀。

**Comment by comehope** [comment]
`filter: contrast()` 用于调整对比度，最强烈的对比是黑色和白色的对比，所以令前景文字 `p` 为白色，令容器 `.container` 的背景为黑色。如果不显式地为 `.container` 设置 `background-color: black`，默认的颜色值并不是黑色而是 `transparent`，虽然容器背景看起来仍是黑色的，但那不是容器本身的背景色，而是因为透明而显示出的 `body` 的背景色。

**Comment by zwmin** [comment]
谢谢指教，有点明白了

**Comment by comehope** [comment]
互相学习哈~
